In [54]:
import sys,os
import pandas as pd
import numpy as np
sys.path.append(os.path.abspath(os.path.join('..')))
from scripts.sequential import ConditionalSPRT
import scipy.stats as scp

In [2]:
df = pd.read_csv("../data/AdSmartABdata.csv")

In [3]:
df.head(3)

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
0,0008ef63-77a7-448b-bd1e-075f42c55e39,exposed,2020-07-10,8,Generic Smartphone,6,Chrome Mobile,0,0
1,000eabc5-17ce-4137-8efe-44734d914446,exposed,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,exposed,2020-07-05,2,E5823,6,Chrome Mobile WebView,0,1

In [ ]:
df.groupby("experiment")

In [78]:
def transform_data(df):
    '''
    segment data into exposed and control groups
    consider that SmartAd runs the experment hourly, group data into hours. 
    Hint: create new column to hold date+hour and use df.column.map(lambda x:  pd.Timestamp(x,tz=None).strftime('%Y-%m-%d:%H'))
    create two dataframes with bernouli series 1 for posetive(yes) and 0 for negative(no)
    Hint: Given engagement(sum of yes and no until current observation as an array) and success (yes countas an array), the method generates random binomial distribution
    #Example
       engagement = np.array([5, 3, 3])
       yes = np.array([2, 0, 3])       
     Output is "[1] 1 0 1 0 0 0 0 0 1 1 1", showing a binary array of 5+3+3 values
     of which 2 of the first 5 are ones, 0 of the next 3 are ones, and all 3 of
     the last 3 are ones where position the ones is randomly distributed within each group.
    '''
    df['hour'] = df.hour.astype(str)
    hours = []
    for i in df['hour']:
        if len(i) < 2:
            hours.append(i.zfill(2))
        else:
            hours.append(i)
    df['hour'] = hours
    df['hour'] = df.hour.astype(str)
    df['date_hour'] =  pd.to_datetime(df['date'] + ' ' + df['hour'] + ':00:00')
    a, b = 0.2, 0.8
    yes = scp.bernoulli .rvs(a, b, size = len(df)) 
    df['bern_yes'] = yes
    a, b = 0.2, 0.8
    no = scp.bernoulli .rvs(a, b, size = len(df)) 
    df['bern_no'] = no
    
    return df

In [79]:
result = transform_data(df)

In [82]:
result.head()

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no,date_hour,bern_yes,bern_no
0,0008ef63-77a7-448b-bd1e-075f42c55e39,exposed,2020-07-10,08,Generic Smartphone,6,Chrome Mobile,0,0,2020-07-10 08:00:00,0,0
1,000eabc5-17ce-4137-8efe-44734d914446,exposed,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0,2020-07-07 10:00:00,1,0
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,exposed,2020-07-05,02,E5823,6,Chrome Mobile WebView,0,1,2020-07-05 02:00:00,0,1
3,00187412-2932-4542-a8ef-3633901c98d9,control,2020-07-03,15,Samsung SM-A705FN,6,Facebook,0,0,2020-07-03 15:00:00,0,0
4,001a7785-d3fe-4e11-a344-c8735acacc2c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0,2020-07-03 15:00:00,0,0

In [87]:
df.head()

,auction_id,experiment,date,hour,device_make,platform_os,browser,yes,no
0,0008ef63-77a7-448b-bd1e-075f42c55e39,exposed,2020-07-10,8,Generic Smartphone,6,Chrome Mobile,0,0
1,000eabc5-17ce-4137-8efe-44734d914446,exposed,2020-07-07,10,Generic Smartphone,6,Chrome Mobile,0,0
2,0016d14a-ae18-4a02-a204-6ba53b52f2ed,exposed,2020-07-05,2,E5823,6,Chrome Mobile WebView,0,1
3,00187412-2932-4542-a8ef-3633901c98d9,control,2020-07-03,15,Samsung SM-A705FN,6,Facebook,0,0
4,001a7785-d3fe-4e11-a344-c8735acacc2c,control,2020-07-03,15,Generic Smartphone,6,Chrome Mobile,0,0

In [4]:
exposed = df[df['experiment']=='exposed']
control = df[df['experiment']=='control']

In [87]:
# from scripts.sequential import ConditionalSPRT
csprt = ConditionalSPRT(exposed['yes'].to_numpy(),control['yes'].to_numpy(),0.064)
results = csprt.ConditionalSPRT(300,exposed['yes'].to_numpy(),control['yes'].to_numpy(),2,1)

In [88]:
results

('Their is no statistically significant difference between two test groups',
 array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
        209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
        222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
        235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
        248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
        261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
        274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
        287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
        300]),
 298,
 -2.251291798606495,
 2.8903717578961645,
 nan,
 'Non',
 array([ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,
        10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 12, 13, 13, 13, 13, 13, 13,
        13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
        13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
        14, 14, 14, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
        17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
        18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,
        19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
        20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], dtype=int64),
 array([ 0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
         5,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10,
        10, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 15, 15, 15, 15,
        15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 18, 18, 18, 18,
        19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 21, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
        23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 26,
        26, 26, 27, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
        30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31,
        31, 31, 31, 31, 31, 31, 31, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33,
        33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,
        33, 33, 33, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 36, 36, 36, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
        38, 38, 38, 38, 38, 38, 38, 39, 40, 41, 41], dtype=int64),
 array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.28768207,  0.28768207,  0.28768207,
         0.28768207,  0.28768207,  0.28768207, -0.11365932, -0.11394426,
        -0.11419237, -0.11441035, -0.11460338, -0.11477551, -0.11492997,
        -0.11506933, -0.11519571, -0.11531085, -0.11541617, -0.11551289,
        -0.51669074, -0.51693897, -0.5171691 , -0.51738302, -0.51758241,
        -0.51776868, -0.51794309, -0.22526584, -0.22557458, -0.22586535,
        -0.22613967, -0.22639891, -0.22664427, -0.22687683, -0.22709758,
        -0.2273074 , -0.22750707, -0.22769731, -0.22787877,  0.06465476,
         0.06437802,  0.06411323,  0.06385963,  0.06361654,  0.0633833 ,
         0.06315933,  0.0629441 , -0.33740094, -0.33770041, -0.33798884,
        -0.33826683, -0.33853493, -0.33879367, -0.04562067, -0.04595928,
        -0.04628664, -0.0466033 , -0.04690978, -0.44649726, -0.44688128,
        -0.44725351, -0.44761449, -0.15363967, -0.15407742, -0.15450251,
        -0.15491547, -0.15531682, -0.15570703, -0.15608657, -0.15645586,
        -0.15681532, -0.15716533, -0.15750627, -0.15783847, -0.15816228,
        -0.158478  , -0.55806465, -0.55844068, -0.55880764, -0.55916588,
        -0.55951569, -0.95884317, -0.95925168, -0.9596509 , -0.66546664,
        -0.66592507, -0.66637342, -0.66681202, -0.66724118, -0.66766121,
        -0.66807239, -0.66847499, -0.6688693 , -0.66925555, -0.66963399,
        -0.67000486, -0.67036839, -0.67072478, -0.67107425, -0.67141699,
        -1.0708437 , -1.07123393, -1.07161685, -1.07199268, -1.07236161,
        -1.07272382, -1.0730795 , -1.07342882, -0.77967019, -0.78006385,
        -0.48597115, -0.48641015, -0.48684163, -0.48726578, -0.4876828 ,
        -0.48809285, -0.88703655, -0.88749024, -0.88793654, -0.88837563,
        -0.88880767, -0.88923284, -0.88965131, -0.89006322, -0.89046873,
        -0.59630929, -0.59675522, -0.99546009, -0.99594708, -0.99642678,
        -0.99689935, -0.70228124, -0.70279439, -0.70330008, -0.70379848,
        -0.70428973, -0.704774  , -0.41008451, -0.41060792, -0.41112404,
        -0.41163302, -0.11678729,  0.17834515,  0.17775051,  0.17716387,
         0.17658509,  0.176014  ,  0.17545046,  0.1748943 ,  0.1743454 ,
         0.1738036 ,  0.17326877,  0.17274078,  0.1722195 ,  0.1717048 ,
        -0.22657133, -0.22712139, -0.22766464, -0.2282012 , -0.22873118,
        -0.22925473, -0.22977194, -0.23028293, -0.23078782, -0.23128671,
        -0.23177972,  0.06294451,  0.06241889,  0.06189936,  0.06138584,
         0.0608782 ,  0.06037635,  0.0598802 ,  0.05938964,  0.05890458,
         0.05842493,  0.0579506 ,  0.05748151,  0.05701755, -0.34160546,
        -0.34209912, -0.74052657, -0.7410502 , -0.74156824, -1.13984085,
        -0.84474458, -0.84532882, -0.55005121, -0.55066603, -0.55127448,
        -0.55187666, -0.55247267, -0.5530626 , -0.55364655, -0.55422459,
        -0.55479684, -0.55536336, -0.55592425, -0.55647958, -0.26138069,
        -0.26196435, -0.26254232, -0.26311468, -0.26368151, -0.26424289,
        -0.2647989 , -0.26534962, -0.26589512, -0.26643547, -0.26697075,
        -0.26750103, -0.26802638, -0.26854686, -0.66681689, -0.66736334,
        -0.6679048 , -0.66844134, -0.66897302, -0.66949991, -0.67002208,
        -0.67053959, -0.67105249, -0.67156085, -0.37676447, -0.7749306 ,
        -0.77549329, -0.77605107, -0.77660403, -0.77715222, -0.7776957 ,
        -0.77823453, -0.77876878, -0.77929849, -0.77982374, -0.78034456,
        -0.78086103, -0.78137319, -0.7818811 , -0.78238481, -0.78288437,
        -0.78337984, -0.78387126, -0.78435868, -0.78484215, -0.78532172,
        -0.78579744, -0.78626935, -0.7867375 , -0.78720193, -0.78766269,
        -0.78811982, -0.78857336, -0.78902336, -1.18777073, -1.18824164,
        -1.1887089 , -0.89419249, -0.89468069, -0.89516515, -0.89564593,
        -0.89612306, -0.89659659, -0.89706656, -0.897533  , -0.89799596,
        -0.89845547, -0.89891158, -0.89936431, -1.29809689, -1.29856942,
        -1.29903849, -1.00451381, -1.00500269, -1.40349426, -1.40400307,
        -1.40450823, -1.40500978, -1.40550775, -1.40600218, -1.40649312,
        -1.40698059, -1.40746464, -1.4079453 , -1.40842261, -1.40889659,
        -1.4093673 , -1.40983475, -1.41029899, -1.41076004, -1.41121794,
        -1.41167272, -1.81039665, -2.20897578, -2.60741151, -2.60792833]),
 array([[-4,  5],
        [-4,  5],
        [-4,  5],
        [-4,  5],
        [-4,  5],
        [-4,  5],
        [-4,  5],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-3,  6],
        [-2,  7],
        [-2,  7],
        [-2,  7],
        [-2,  7],
        [-2,  7],
        [-2,  7],
        [-2,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  7],
        [-1,  8],
        [-1,  8],
        [-1,  8],
        [-1,  8],
        [-1,  8],
        [-1,  8],
        [-1,  8],
        [-1,  8],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 0,  9],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 1, 10],
        [ 2, 11],
        [ 2, 11],
        [ 2, 11],
        [ 2, 11],
        [ 2, 11],
        [ 3, 11],
        [ 3, 11],
        [ 3, 11],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 3, 12],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 4, 13],
        [ 5, 14],
        [ 5, 14],
        [ 5, 14],
        [ 5, 14],
        [ 5, 14],
        [ 5, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 14],
        [ 6, 15],
        [ 6, 15],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 7, 16],
        [ 8, 17],
        [ 8, 17],
        [ 8, 17],
        [ 8, 17],
        [ 8, 17],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [ 9, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 18],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [10, 19],
        [11, 20],
        [11, 20],
        [11, 20],
        [11, 20],
        [11, 20],
        [12, 21],
        [12, 21],
        [12, 21],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [13, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 22],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [14, 23],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [15, 24],
        [16, 25],
        [16, 25],
        [16, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 25],
        [17, 26],
        [17, 26],
        [17, 26],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [18, 27],
        [19, 28],
        [19, 28],
        [20, 29],
        [20, 29]]))

In [119]:
val